# Generated by Django 2.2.2 on 2019-06-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PanelsForGame', '0002_auto_20190623_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personage',
            old_name='user_id',
            new_name='user',
        ),
    ]
