# Generated by Django 2.2.2 on 2019-06-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelsForGame', '0003_auto_20190623_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personage',
            name='date_last_input',
            field=models.DateTimeField(help_text='Дата последнего входа', null=True),
        ),
    ]
