# Generated by Django 2.2.2 on 2019-06-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelsForGame', '0004_auto_20190624_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagetransfer',
            name='date_last_visit',
            field=models.DateTimeField(help_text='Последняя дата визита локации', null=True),
        ),
    ]
