# Generated by Django 2.2.2 on 2019-06-23 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PanelsForGame', '0006_auto_20190624_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personage',
            name='date_last_input',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 24, 2, 28, 47, 187898), help_text='Дата последнего входа'),
        ),
        migrations.AlterField(
            model_name='personagetransfer',
            name='date_last_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 24, 2, 28, 47, 189893), help_text='Последняя дата визита локации'),
        ),
    ]
